site_name: ICPSR Metadata Documentation Portal
site_url: https://icpsr.github.io/metadata/
docs_dir: ../markdown
site_dir: ../site
nav:
  - ICPSR Metadata Home: index.md
  - Curated Study Metadata Schema: icpsr_study_schema.md
  - Metadata Entry Style Guide: icpsr_style_guide.md
  - Documentation Version History: version_history.md
theme:
  name: readthedocs
  prev_next_buttons_location: none
