name: Update ICPSR Markdown

on:
  push:
    branches-ignore:
      - main
      - gh-pages
    paths:
      - 'schema/**'
      - 'rde_schema/**'

jobs:
  update_markdown:
    runs-on: ubuntu-latest
    name: Update Markdown

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files in schema folder
        id: changed-schema
        uses: tj-actions/changed-files@v44
        with:
          files: schema/**

      - name: Get changed files in rde_schema folder
        id: changed-rde
        uses: tj-actions/changed-files@v44
        with:
          files: rde_schema/**

      - name: Prevent running if no relevant files changed
        if: steps.changed-schema.outputs.any_changed != 'true' && steps.changed-rde.outputs.any_changed != 'true'
        run: echo "No relevant changes detected"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r resources/requirements.txt

      - name: Generate Legacy Schema Documentation
        if: steps.changed-schema.outputs.any_changed == 'true'
        run: |
          python resources/generate_markdown.py \
            --input $GITHUB_WORKSPACE \
            --mode legacy

      - name: Generate Current Schema Documentation
        if: steps.changed-rde.outputs.any_changed == 'true'
        run: |
          python resources/generate_markdown.py \
            --input $GITHUB_WORKSPACE \
            --mode current

      - name: Commit and push changes
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          git add markdown/
          git diff --cached --quiet || git commit -m "Generated new copy of schema in markdown"
          git push origin HEAD:$GITHUB_REF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site